# Generated by Django 5.1.2 on 2024-10-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='brand',
        ),
    ]
