# Generated by Django 5.1.2 on 2024-10-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_year_product_operating_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Operating_System',
            new_name='operating_System',
        ),
    ]
