# Generated by Django 5.1.2 on 2024-10-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cpu_speed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
