# Generated by Django 5.1.2 on 2024-10-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_product_cpu_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operating_System',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
